/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/planetWithSatellite.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_1.geometry} material={materials.PlanetMat} />
      <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.005']} />
    </group>
  )
}

useGLTF.preload('/planetWithSatellite.glb')
