/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

//TODO: Change URL for live-url on production. 
const modelURL = 'https://tubular-sunburst-06da0f.netlify.app/models/planetdemo.glb';
export default function Model(props) {
  const { nodes, materials } = useGLTF(modelURL)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials.PlanetMat} scale={6.47} />
    </group>
  )
}

useGLTF.preload(modelURL)
